### ISSUE TITLE
about the DWT

### ISSUE THREAD

**Issue by KwanWaiPang** [boyuzz/WMCNN-Pytorch#1]
hello~can you tell my how to relasize the DWT in pytorch？ thank you

**Comment by boyuzz** [comment]
@KwanWaiPang I'm not sure how to implement DWT in pytorch. But if you just want to implement that in python, you can check [data_generator.py](https://github.com/boyuzz/WMCNN-Pytorch/blob/33747b9863639d358d79379080a24f4e0fa065fc/data_generator.py#L97).
