### ISSUE TITLE
id_files.txt is missing 

### ISSUE THREAD

**Issue by Dr-FarahDeeba-Memon** [boyuzz/WMCNN-Pytorch#2]
id_files.txt
i am facing this issue. that this txt file is not present. can you please solve my this issue

**Comment by boyuzz** [comment]
@farah32 Sorry for late reply. The "id_files.txt" is just used to specify the locations of the images (eg,../aGrass/a001.jpg, ../aGrass/a002.jpg, ...). You can download this file in [this site](https://www.dropbox.com/s/j80iv1a0mvhonsa/RSSCN7.zip?dl=0), which also provides the split of training and testing set.

**Comment by kingloser** [comment]
> @farah32 Sorry for late reply. The "id_files.txt" is just used to specify the locations of the images (eg,../aGrass/a001.jpg, ../aGrass/a002.jpg, ...). You can download this file in [this site](https://www.dropbox.com/s/j80iv1a0mvhonsa/RSSCN7.zip?dl=0), which also provides the split of training and testing set.
this url is 404,can you share a new url ?

**Comment by boyuzz** [comment]
@kingloser Hi, I've uploaded the id_files.txt [here](https://github.com/boyuzz/WMCNN-Pytorch/blob/master/data/rsscn7/id_files.txt).

**Comment by kingloser** [comment]
> @kingloser Hi, I've uploaded the id_files.txt [here](https://github.com/boyuzz/WMCNN-Pytorch/blob/master/data/rsscn7/id_files.txt).

thank you very much

**Comment by boyuzz** [comment]
@kingloser You are welcome. 

Then I'll close this issue.

**Comment by minaahmed** [comment]
@boyuzz  Hi the link for downloading dataset is not working, could you please share the link?

**Comment by boyuzz** [comment]
> @boyuzz Hi the link for downloading dataset is not working, could you please share the link?

Hi, I've updated the link by https://github.com/palewithout/RSSCN7.

**Comment by minaahmed** [comment]
@boyuzz thanks a lot, but you mentioned the dataset is already splitted between training and testing, it is not there in the link?

**Comment by boyuzz** [comment]
> @boyuzz thanks a lot, but you mentioned the dataset is already splitted between training and testing, it is not there in the link?

No, the original dataset is not splitted. The original dataset is splitted during dataset generation, which randomly selects 70% images from each class for training and the left for testing.

**Comment by minaahmed** [comment]
@boyuzz Great, thanks
